[![Travis-CI Build
Status](https://travis-ci.com/jhsiao999/peco.svg?branch=master)](https://travis-ci.com/jhsiao999/peco)
[![AppVeyor build
status](https://ci.appveyor.com/api/projects/status/github/jhsiao999/peco?branch=master&svg=true)](https://ci.appveyor.com/project/jhsiao999/peco)
[![CircleCI build
status](https://circleci.com/gh/jhsiao999/peco.svg?style=svg)](https://circleci.com/gh/jhsiao999/peco)
[![License: GPL
v3](https://img.shields.io/badge/License-GPL%20v3-blue.svg)](http://www.gnu.org/licenses/gpl-3.0)

## peco

**peco** is an R package for **P**r**E**dicting **C**ell cycle
pr**O**gression in a continuum using scRNA-seq data.

### Installation

To install and load the package, run:

``` r
install.packages("devtools")
library(devtools)
install_github("jhsiao999/peco")
```

`peco` uses `SingleCellExperiment` class objects.

``` r
library(peco)
library(SingleCellExperiment)
library(doParallel)
library(foreach)
```

### Overview

`peco` is a supervised approach for PrEdicting cell cycle phase in a
COntinuum using single-cell RNA sequencing data. The R package provides
functions to build training dataset and also functions to use existing
training data to predict cell cycle on a continuum.

Our work demonstrated that peco is able to predict continuous cell cylce
phase using a small set of cylcic genes: *CDK1*, *UBE2C*, *TOP2A*,
*HISTH1E*, and *HISTH1C* (identified as cell cycle marker genes in
studies of yeast (\[Spellman et al., 1998\]\[spellman\]) and HeLa cells
(\[Whitfield et al., 2002\]\[whitfield\])).

Below we provide two use cases. Vignette 1 shows how to use the
built-training dataset to predict continuous cell cycle. Vignette 2
shows how to make a training datast and build a predictor using training
data.

Users can also view the vigenettes via `browseVignettes("peco")`.

### Vignette 1: Using built-in training data

`training_human` stores built-in training data of 101 significant cyclic
genes. Below are the slots contained in `training_human`:

  - `predict.yy`: a gene by sample matrix (101 by 888) that stores
    predict cyclic expression values.
  - `cellcycle_peco_reordered`: cell cycle phase in a unit circle
    (angle), ordered from 0 to 2\(pi\)
  - `cellcycle_function`: lists of 101 function corresponding to the top
    101 cyclic genes identified in our dataset
  - `sigma`: standard error associated with cyclic trends of gene
    expression
  - `pve`: proportion of variance explained by the cyclic trend

<!-- end list -->

``` r
data("training_human")
str(training_human)
```

    ## List of 5
    ##  $ predict.yy            : num [1:101, 1:888] -0.6282 -0.1886 -0.1829 -0.1413 0.0138 ...
    ##   ..- attr(*, "dimnames")=List of 2
    ##   .. ..$ : chr [1:101] "ENSG00000170312" "ENSG00000175063" "ENSG00000131747" "ENSG00000198518" ...
    ##   .. ..$ : chr [1:888] "20170919-H12" "20170908-D11" "20170924-F03" "20170906-A01" ...
    ##  $ cellcycle_peco_ordered: Named num [1:888] 0.00391 0.0091 0.02638 0.03694 0.04366 ...
    ##   ..- attr(*, "names")= chr [1:888] "20170919-H12" "20170908-D11" "20170924-F03" "20170906-A01" ...
    ##  $ cellcycle_function    :List of 101
    ##   ..$ ENSG00000170312:function (v)  
    ##   ..$ ENSG00000175063:function (v)  
    ##   ..$ ENSG00000131747:function (v)  
    ##   ..$ ENSG00000198518:function (v)  
    ##   ..$ ENSG00000197061:function (v)  
    ##   ..$ ENSG00000150991:function (v)  
    ##   ..$ ENSG00000143476:function (v)  
    ##   ..$ ENSG00000117724:function (v)  
    ##   ..$ ENSG00000154473:function (v)  
    ##   ..$ ENSG00000065328:function (v)  
    ##   ..$ ENSG00000094804:function (v)  
    ##   ..$ ENSG00000182481:function (v)  
    ##   ..$ ENSG00000137807:function (v)  
    ##   ..$ ENSG00000087586:function (v)  
    ##   ..$ ENSG00000123975:function (v)  
    ##   ..$ ENSG00000123485:function (v)  
    ##   ..$ ENSG00000132646:function (v)  
    ##   ..$ ENSG00000198826:function (v)  
    ##   ..$ ENSG00000102409:function (v)  
    ##   ..$ ENSG00000184047:function (v)  
    ##   ..$ ENSG00000198901:function (v)  
    ##   ..$ ENSG00000124529:function (v)  
    ##   ..$ ENSG00000112312:function (v)  
    ##   ..$ ENSG00000080986:function (v)  
    ##   ..$ ENSG00000148773:function (v)  
    ##   ..$ ENSG00000179820:function (v)  
    ##   ..$ ENSG00000237649:function (v)  
    ##   ..$ ENSG00000111665:function (v)  
    ##   ..$ ENSG00000134690:function (v)  
    ##   ..$ ENSG00000140451:function (v)  
    ##   ..$ ENSG00000168496:function (v)  
    ##   ..$ ENSG00000189159:function (v)  
    ##   ..$ ENSG00000132424:function (v)  
    ##   ..$ ENSG00000142945:function (v)  
    ##   ..$ ENSG00000112742:function (v)  
    ##   ..$ ENSG00000076003:function (v)  
    ##   ..$ ENSG00000105173:function (v)  
    ##   ..$ ENSG00000101412:function (v)  
    ##   ..$ ENSG00000136108:function (v)  
    ##   ..$ ENSG00000163535:function (v)  
    ##   ..$ ENSG00000197756:function (v)  
    ##   ..$ ENSG00000069275:function (v)  
    ##   ..$ ENSG00000079246:function (v)  
    ##   ..$ ENSG00000101447:function (v)  
    ##   ..$ ENSG00000083845:function (v)  
    ##   ..$ ENSG00000178999:function (v)  
    ##   ..$ ENSG00000083312:function (v)  
    ##   ..$ ENSG00000024526:function (v)  
    ##   ..$ ENSG00000138778:function (v)  
    ##   ..$ ENSG00000092201:function (v)  
    ##   ..$ ENSG00000136485:function (v)  
    ##   ..$ ENSG00000104738:function (v)  
    ##   ..$ ENSG00000088325:function (v)  
    ##   ..$ ENSG00000156802:function (v)  
    ##   ..$ ENSG00000160799:function (v)  
    ##   ..$ ENSG00000196230:function (v)  
    ##   ..$ ENSG00000173207:function (v)  
    ##   ..$ ENSG00000198558:function (v)  
    ##   ..$ ENSG00000117523:function (v)  
    ##   ..$ ENSG00000170779:function (v)  
    ##   ..$ ENSG00000174371:function (v)  
    ##   ..$ ENSG00000123219:function (v)  
    ##   ..$ ENSG00000167900:function (v)  
    ##   ..$ ENSG00000169607:function (v)  
    ##   ..$ ENSG00000144713:function (v)  
    ##   ..$ ENSG00000143614:function (v)  
    ##   ..$ ENSG00000164045:function (v)  
    ##   ..$ ENSG00000130182:function (v)  
    ##   ..$ ENSG00000253729:function (v)  
    ##   ..$ ENSG00000163159:function (v)  
    ##   ..$ ENSG00000135245:function (v)  
    ##   ..$ ENSG00000116288:function (v)  
    ##   ..$ ENSG00000166405:function (v)  
    ##   ..$ ENSG00000232112:function (v)  
    ##   ..$ ENSG00000143799:function (v)  
    ##   ..$ ENSG00000106028:function (v)  
    ##   ..$ ENSG00000135083:function (v)  
    ##   ..$ ENSG00000134308:function (v)  
    ##   ..$ ENSG00000126267:function (v)  
    ##   ..$ ENSG00000129810:function (v)  
    ##   ..$ ENSG00000184661:function (v)  
    ##   ..$ ENSG00000112118:function (v)  
    ##   ..$ ENSG00000152253:function (v)  
    ##   ..$ ENSG00000117399:function (v)  
    ##   ..$ ENSG00000168653:function (v)  
    ##   ..$ ENSG00000100297:function (v)  
    ##   ..$ ENSG00000211450:function (v)  
    ##   ..$ ENSG00000182899:function (v)  
    ##   ..$ ENSG00000172809:function (v)  
    ##   ..$ ENSG00000040275:function (v)  
    ##   ..$ ENSG00000092853:function (v)  
    ##   ..$ ENSG00000128951:function (v)  
    ##   ..$ ENSG00000167670:function (v)  
    ##   ..$ ENSG00000118193:function (v)  
    ##   ..$ ENSG00000170043:function (v)  
    ##   ..$ ENSG00000143933:function (v)  
    ##   ..$ ENSG00000125743:function (v)  
    ##   ..$ ENSG00000092140:function (v)  
    ##   ..$ ENSG00000162613:function (v)  
    ##   .. [list output truncated]
    ##  $ sigma                 :'data.frame':  101 obs. of  1 variable:
    ##   ..$ sigma: num [1:101] 0.844 0.882 0.908 0.971 1.003 ...
    ##  $ pve                   :'data.frame':  101 obs. of  1 variable:
    ##   ..$ pve: num [1:101] 0.2903 0.2251 0.1778 0.0882 0.0288 ...

`peco` is integrated with `SingleCellExperiment` object in Bioconductor.
Below shows an example of inputting `SingleCellExperiment` object to
perform cell cycle phase prediction.

`sce_top101genes` includes 101 genes and 888 single-cell samples and one
assay slot of `counts`.

``` r
data("sce_top101genes")
assays(sce_top101genes)
```

    ## List of length 1
    ## names(1): counts

Transform the expression values to quantile-normalizesd
counts-per-million values. `peco` uses the `cpm_quantNormed` slot as
input data for predictions.

``` r
sce_top101genes <- data_transform_quantile(sce_top101genes)
```

    ## computing on 2 cores

``` r
assays(sce_top101genes)
```

    ## List of length 3
    ## names(3): counts cpm cpm_quantNormed

Apply the prediction model using function `cycle_npreg_outsample`.

``` r
model_101genes_predict <- cycle_npreg_outsample(
    Y_test=sce_top101genes,
    sigma_est=training_human$sigma[rownames(sce_top101genes),],
    funs_est=training_human$cellcycle_function[rownames(sce_top101genes)],
    method.trend="trendfilter",
    ncores=1,
    get_trend_estimates=FALSE)
```

`peco` adds the predict cell cycle phase to the `colData` slot.
sce\_top101genes

``` r
colData(model_101genes_predict)$cellcycle_peco
```

    ## 20170905-A01 20170905-A02 20170905-A03 20170905-A06 20170905-A07 
    ##   1.09955743   4.68097305   2.67035376   4.30398194   4.05265452 
    ## 20170905-A08 20170905-A09 20170905-A10 20170905-A11 20170905-A12 
    ##   1.41371669   1.22522113   4.68097305   1.16238928   3.67566340 
    ## 20170905-B03 20170905-B04 20170905-B05 20170905-B07 20170905-B08 
    ##   1.97920337   1.09955743   1.66504411   1.28805299   1.97920337 
    ## 20170905-B09 20170905-B10 20170905-B11 20170905-C01 20170905-C02 
    ##   4.99513232   5.74911456   1.60221225   4.24115008   4.42964564 
    ## 20170905-C03 20170905-C04 20170905-C06 20170905-C07 20170905-C08 
    ##   1.35088484   1.53938040   0.15707963   1.47654855   1.85353967 
    ## 20170905-C10 20170905-C11 20170905-C12 20170905-D01 20170905-D03 
    ##   6.25176938   1.85353967   1.91637152   4.30398194   2.48185820 
    ## 20170905-D04 20170905-D06 20170905-D07 20170905-D08 20170905-D09 
    ##   1.28805299   4.49247749   1.09955743   1.35088484   1.66504411 
    ## 20170905-D10 20170905-E01 20170905-E02 20170905-E03 20170905-E07 
    ##   1.09955743   1.66504411   4.24115008   1.03672558   4.24115008 
    ## 20170905-E08 20170905-E09 20170905-E11 20170905-E12 20170905-F01 
    ##   5.93761012   4.42964564   1.47654855   0.03141593   1.28805299 
    ## 20170905-F02 20170905-F04 20170905-F06 20170905-F07 20170905-F10 
    ##   1.41371669   1.91637152   4.24115008   5.74911456   1.28805299 
    ## 20170905-F11 20170905-F12 20170905-G01 20170905-G02 20170905-G04 
    ##   1.47654855   4.17831823   1.97920337   1.60221225   4.42964564 
    ## 20170905-G05 20170905-G06 20170905-G07 20170905-G09 20170905-G10 
    ##   1.16238928   4.42964564   4.36681379   1.03672558   1.47654855 
    ## 20170905-G11 20170905-H03 20170905-H04 20170905-H05 20170905-H06 
    ##   1.47654855   1.16238928   1.47654855   1.47654855   1.09955743 
    ## 20170905-H07 20170905-H10 20170905-H12 20170906-A01 20170906-A03 
    ##   0.91106187   6.06327382   1.35088484   5.49778714   4.49247749 
    ## 20170906-A04 20170906-A06 20170906-A08 20170906-B01 20170906-B02 
    ##   3.04734487   3.80132711   0.91106187   4.17831823   3.67566340 
    ## 20170906-B03 20170906-B04 20170906-B05 20170906-B07 20170906-B08 
    ##   1.28805299   1.85353967   4.24115008   4.93230047   1.16238928 
    ## 20170906-B09 20170906-B12 20170906-C01 20170906-C02 20170906-C03 
    ##   4.30398194   0.03141593   1.85353967   1.60221225   1.97920337 
    ## 20170906-C04 20170906-C05 20170906-C06 20170906-C07 20170906-C08 
    ##   5.24645973   0.34557519   4.30398194   1.66504411   1.91637152 
    ## 20170906-C09 20170906-C11 20170906-C12 20170906-D01 20170906-D02 
    ##   0.84823002   4.42964564   4.24115008   1.60221225   0.28274334 
    ## 20170906-D05 20170906-D07 20170906-D08 20170906-D10 20170906-D11 
    ##   1.79070781   3.80132711   1.47654855   1.47654855   4.11548638 
    ## 20170906-D12 20170906-E04 20170906-E05 20170906-E06 20170906-E07 
    ##   1.09955743   4.17831823   0.59690260   1.72787596   1.16238928 
    ## 20170906-E08 20170906-E09 20170906-E11 20170906-F01 20170906-F02 
    ##   3.11017673   0.72256631   0.47123890   4.68097305   1.41371669 
    ## 20170906-F08 20170906-F10 20170906-G02 20170906-G03 20170906-G05 
    ##   5.05796417   3.92699082   4.42964564   1.28805299   2.60752190 
    ## 20170906-G06 20170906-G07 20170906-G08 20170906-G09 20170906-G11 
    ##   5.74911456   4.11548638   4.17831823   4.30398194   4.42964564 
    ## 20170906-G12 20170906-H01 20170906-H03 20170906-H04 20170906-H07 
    ##   4.30398194   1.09955743   6.25176938   1.47654855   4.42964564 
    ## 20170906-H09 20170906-H10 20170906-H11 20170906-H12 20170907-A02 
    ##   4.55530935   6.00044197   5.18362788   0.78539816   1.16238928 
    ## 20170907-A05 20170907-A06 20170907-A12 20170907-B05 20170907-B06 
    ##   1.97920337   4.68097305   4.42964564   1.53938040   1.03672558 
    ## 20170907-B07 20170907-B08 20170907-B09 20170907-B10 20170907-B11 
    ##   1.97920337   4.17831823   1.91637152   1.16238928   0.84823002 
    ## 20170907-C01 20170907-C02 20170907-C04 20170907-C05 20170907-C06 
    ##   1.41371669   1.16238928   0.78539816   3.86415896   1.79070781 
    ## 20170907-D01 20170907-D03 20170907-D05 20170907-D06 20170907-D09 
    ##   1.16238928   4.86946861   1.66504411   0.84823002   4.11548638 
    ## 20170907-D10 20170907-D11 20170907-D12 20170907-E03 20170907-E06 
    ##   1.28805299   4.93230047   1.03672558   5.62345085   0.34557519 
    ## 20170907-E07 20170907-E10 20170907-E12 20170907-F05 20170907-F06 
    ##   1.09955743   0.59690260   1.47654855   0.78539816   1.09955743 
    ## 20170907-F10 20170907-F11 20170907-F12 20170907-G01 20170907-G04 
    ##   1.79070781   1.91637152   1.85353967   1.16238928   2.23053078 
    ## 20170907-G05 20170907-G07 20170907-G09 20170907-G10 20170907-G11 
    ##   2.79601746   0.91106187   1.47654855   1.53938040   1.16238928 
    ## 20170907-G12 20170907-H02 20170907-H04 20170907-H05 20170907-H06 
    ##   1.16238928   1.66504411   0.40840704   1.66504411   1.22522113 
    ## 20170907-H07 20170907-H10 20170907-H11 20170908-A01 20170908-A02 
    ##   1.16238928   1.53938040   1.16238928   5.12079603   4.05265452 
    ## 20170908-A03 20170908-A04 20170908-A06 20170908-A07 20170908-A08 
    ##   5.24645973   1.16238928   0.40840704   6.25176938   5.62345085 
    ## 20170908-A09 20170908-A10 20170908-A11 20170908-B02 20170908-B03 
    ##   4.11548638   1.22522113   1.28805299   3.04734487   3.11017673 
    ## 20170908-B05 20170908-B06 20170908-B07 20170908-B08 20170908-B09 
    ##   1.53938040   1.28805299   4.11548638   3.80132711   1.60221225 
    ## 20170908-B10 20170908-B11 20170908-B12 20170908-C01 20170908-C02 
    ##   4.93230047   1.53938040   1.28805299   3.61283155   1.60221225 
    ## 20170908-C03 20170908-C06 20170908-C10 20170908-D02 20170908-D04 
    ##   1.16238928   1.97920337   1.16238928   2.35619449   1.72787596 
    ## 20170908-D05 20170908-D06 20170908-D07 20170908-D09 20170908-D10 
    ##   1.16238928   1.03672558   1.53938040   1.28805299   1.91637152 
    ## 20170908-D11 20170908-E01 20170908-E02 20170908-E03 20170908-E05 
    ##   5.62345085   5.49778714   1.60221225   1.66504411   4.93230047 
    ## 20170908-E08 20170908-E10 20170908-E11 20170908-F01 20170908-F02 
    ##   0.15707963   2.41902634   1.16238928   1.60221225   4.17831823 
    ## 20170908-F03 20170908-F05 20170908-F06 20170908-F07 20170908-F09 
    ##   1.60221225   1.41371669   1.03672558   4.11548638   1.97920337 
    ## 20170908-F10 20170908-F11 20170908-F12 20170908-G03 20170908-G05 
    ##   6.25176938   3.29867229   4.42964564   0.15707963   0.59690260 
    ## 20170908-G06 20170908-G07 20170908-G08 20170908-G10 20170908-G11 
    ##   4.42964564   1.47654855   2.98451302   0.65973446   0.21991149 
    ## 20170908-G12 20170908-H02 20170908-H07 20170908-H09 20170908-H10 
    ##   1.22522113   3.54999970   0.72256631   4.24115008   0.21991149 
    ## 20170910-A02 20170910-A07 20170910-A08 20170910-A10 20170910-A11 
    ##   1.60221225   4.42964564   4.24115008   1.85353967   3.54999970 
    ## 20170910-B01 20170910-B03 20170910-B04 20170910-B05 20170910-B06 
    ##   1.03672558   1.35088484   1.66504411   1.60221225   1.09955743 
    ## 20170910-B07 20170910-B11 20170910-B12 20170910-C01 20170910-C02 
    ##   0.91106187   3.54999970   1.53938040   1.09955743   0.15707963 
    ## 20170910-C07 20170910-C08 20170910-C12 20170910-D04 20170910-D05 
    ##   3.23584043   1.41371669   1.16238928   3.29867229   1.16238928 
    ## 20170910-D06 20170910-D07 20170910-D08 20170910-D09 20170910-D10 
    ##   1.53938040   1.41371669   1.91637152   1.66504411   1.22522113 
    ## 20170910-D12 20170910-E02 20170910-E03 20170910-E04 20170910-E05 
    ##   1.91637152   0.97389372   0.53407075   0.15707963   0.47123890 
    ## 20170910-E07 20170910-E09 20170910-E10 20170910-E12 20170910-F01 
    ##   1.35088484   3.86415896   1.22522113   1.85353967   1.66504411 
    ## 20170910-F03 20170910-F05 20170910-F06 20170910-F07 20170910-F08 
    ##   6.25176938   1.53938040   2.04203522   2.29336264   1.47654855 
    ## 20170910-F09 20170910-F10 20170910-F11 20170910-G04 20170910-G05 
    ##   1.72787596   1.28805299   0.03141593   0.72256631   1.47654855 
    ## 20170910-G06 20170910-G09 20170910-G10 20170910-H01 20170910-H06 
    ##   4.17831823   1.47654855   1.28805299   0.40840704   3.17300858 
    ## 20170910-H10 20170910-H11 20170910-H12 20170912-A01 20170912-A02 
    ##   1.09955743   0.28274334   0.78539816   1.53938040   1.66504411 
    ## 20170912-A03 20170912-A05 20170912-A07 20170912-A11 20170912-A12 
    ##   0.91106187   4.11548638   1.09955743   3.73849526   4.24115008 
    ## 20170912-B01 20170912-B02 20170912-B04 20170912-B05 20170912-B06 
    ##   1.16238928   1.85353967   1.09955743   3.86415896   4.36681379 
    ## 20170912-B07 20170912-B09 20170912-B10 20170912-B11 20170912-B12 
    ##   2.67035376   1.97920337   3.73849526   4.42964564   6.25176938 
    ## 20170912-C02 20170912-C03 20170912-C04 20170912-C05 20170912-C07 
    ##   2.41902634   6.25176938   0.21991149   0.91106187   3.86415896 
    ## 20170912-C08 20170912-C09 20170912-C10 20170912-C11 20170912-C12 
    ##   1.09955743   4.11548638   2.41902634   1.03672558   1.41371669 
    ## 20170912-D01 20170912-D02 20170912-D03 20170912-D04 20170912-D05 
    ##   1.16238928   1.16238928   1.53938040   1.72787596   4.17831823 
    ## 20170912-D06 20170912-D07 20170912-D08 20170912-D09 20170912-D10 
    ##   1.35088484   1.22522113   1.03672558   1.03672558   1.60221225 
    ## 20170912-D11 20170912-D12 20170912-E01 20170912-E02 20170912-E03 
    ##   1.03672558   1.60221225   3.04734487   5.93761012   4.93230047 
    ## 20170912-E04 20170912-E05 20170912-E06 20170912-E09 20170912-E10 
    ##   5.62345085   0.03141593   4.99513232   5.56061900   4.05265452 
    ## 20170912-E11 20170912-E12 20170912-F01 20170912-F02 20170912-F04 
    ##   0.84823002   1.41371669   4.24115008   3.54999970   4.24115008 
    ## 20170912-F05 20170912-F06 20170912-F07 20170912-F08 20170912-F10 
    ##   3.92699082   0.21991149   1.66504411   4.24115008   0.97389372 
    ## 20170912-F12 20170912-G01 20170912-G02 20170912-G03 20170912-G04 
    ##   3.29867229   1.16238928   4.11548638   4.11548638   0.21991149 
    ## 20170912-G05 20170912-G07 20170912-G08 20170912-G11 20170912-G12 
    ##   2.04203522   1.47654855   0.84823002   1.28805299   4.17831823 
    ## 20170912-H01 20170912-H02 20170912-H03 20170912-H04 20170912-H05 
    ##   1.28805299   1.22522113   6.00044197   1.28805299   0.03141593 
    ## 20170912-H06 20170912-H07 20170912-H08 20170912-H10 20170912-H11 
    ##   0.03141593   4.24115008   1.97920337   4.36681379   1.16238928 
    ## 20170912-H12 20170913-A01 20170913-A04 20170913-A06 20170913-A09 
    ##   0.84823002   4.05265452   2.23053078   2.92168117   3.80132711 
    ## 20170913-A12 20170913-B04 20170913-B05 20170913-B06 20170913-B09 
    ##   4.17831823   1.16238928   0.78539816   4.36681379   1.53938040 
    ## 20170913-B11 20170913-C03 20170913-C07 20170913-C10 20170913-C11 
    ##   3.98982267   1.16238928   0.21991149   0.03141593   3.48716785 
    ## 20170913-D01 20170913-D04 20170913-D05 20170913-D06 20170913-D10 
    ##   4.05265452   4.30398194   4.24115008   4.05265452   1.66504411 
    ## 20170913-E02 20170913-E03 20170913-E04 20170913-E06 20170913-E10 
    ##   4.17831823   4.17831823   1.09955743   4.24115008   4.11548638 
    ## 20170913-E11 20170913-F01 20170913-F03 20170913-F04 20170913-F09 
    ##   4.42964564   1.60221225   5.49778714   1.53938040   5.05796417 
    ## 20170913-F10 20170913-F11 20170913-F12 20170913-G01 20170913-G05 
    ##   3.36150414   4.11548638   0.15707963   0.91106187   0.21991149 
    ## 20170913-G06 20170913-G07 20170913-G09 20170913-G11 20170913-H01 
    ##   5.81194641   4.05265452   4.24115008   1.41371669   5.56061900 
    ## 20170913-H02 20170913-H03 20170913-H04 20170913-H05 20170913-H06 
    ##   4.42964564   4.17831823   4.17831823   3.86415896   3.23584043 
    ## 20170913-H08 20170913-H09 20170913-H10 20170913-H11 20170914-A01 
    ##   4.24115008   4.36681379   4.24115008   1.47654855   1.03672558 
    ## 20170914-A02 20170914-A03 20170914-A05 20170914-A06 20170914-A09 
    ##   1.72787596   6.25176938   4.11548638   3.36150414   1.16238928 
    ## 20170914-A10 20170914-A12 20170914-B01 20170914-B02 20170914-B03 
    ##   5.62345085   4.17831823   2.29336264   3.29867229   4.17831823 
    ## 20170914-B07 20170914-B09 20170914-B10 20170914-B12 20170914-C03 
    ##   4.17831823   0.91106187   3.80132711   0.72256631   6.25176938 
    ## 20170914-C05 20170914-C06 20170914-C08 20170914-C10 20170914-C12 
    ##   2.10486708   1.60221225   0.91106187   1.47654855   5.62345085 
    ## 20170914-D06 20170914-D07 20170914-D08 20170914-D09 20170914-D10 
    ##   1.72787596   1.79070781   5.30929158   5.87477826   3.11017673 
    ## 20170914-D12 20170914-E05 20170914-E06 20170914-E09 20170914-E10 
    ##   4.42964564   4.11548638   2.16769893   2.67035376   3.36150414 
    ## 20170914-E11 20170914-E12 20170914-F02 20170914-F04 20170914-F05 
    ##   4.42964564   2.54469005   4.30398194   1.47654855   4.24115008 
    ## 20170914-F06 20170914-F07 20170914-F08 20170914-F10 20170914-F11 
    ##   4.49247749   3.98982267   5.37212344   0.72256631   4.05265452 
    ## 20170914-G02 20170914-G03 20170914-G04 20170914-G05 20170914-G06 
    ##   1.97920337   1.91637152   3.42433599   4.11548638   3.36150414 
    ## 20170914-G10 20170914-H02 20170914-H03 20170914-H04 20170914-H05 
    ##   5.74911456   1.72787596   1.79070781   4.17831823   1.91637152 
    ## 20170914-H06 20170914-H07 20170914-H08 20170914-H10 20170914-H11 
    ##   0.72256631   2.92168117   1.60221225   4.17831823   5.43495529 
    ## 20170914-H12 20170915-A02 20170915-A04 20170915-A05 20170915-A08 
    ##   2.92168117   4.17831823   4.42964564   5.43495529   4.30398194 
    ## 20170915-A09 20170915-A12 20170915-B01 20170915-B02 20170915-B03 
    ##   1.79070781   1.16238928   1.16238928   4.24115008   3.86415896 
    ## 20170915-B04 20170915-B05 20170915-B06 20170915-B08 20170915-B10 
    ##   4.17831823   4.30398194   1.85353967   4.11548638   4.36681379 
    ## 20170915-B12 20170915-C01 20170915-C02 20170915-C03 20170915-C05 
    ##   1.91637152   4.99513232   4.42964564   4.49247749   1.09955743 
    ## 20170915-C06 20170915-C07 20170915-C08 20170915-C11 20170915-D01 
    ##   4.17831823   0.40840704   4.55530935   4.11548638   4.93230047 
    ## 20170915-D02 20170915-D03 20170915-D06 20170915-D07 20170915-D08 
    ##   1.16238928   2.54469005   1.28805299   1.85353967   1.60221225 
    ## 20170915-D11 20170915-E01 20170915-E02 20170915-E03 20170915-E04 
    ##   1.53938040   4.49247749   4.93230047   4.24115008   6.25176938 
    ## 20170915-E05 20170915-E07 20170915-E08 20170915-E10 20170915-F01 
    ##   0.72256631   1.47654855   4.86946861   3.04734487   5.49778714 
    ## 20170915-F03 20170915-F05 20170915-F08 20170915-F10 20170915-F11 
    ##   1.53938040   0.03141593   1.60221225   3.92699082   1.28805299 
    ## 20170915-G01 20170915-G02 20170915-G04 20170915-G05 20170915-G08 
    ##   4.93230047   4.17831823   1.35088484   1.60221225   1.53938040 
    ## 20170915-G09 20170915-G10 20170915-H01 20170915-H04 20170915-H06 
    ##   0.84823002   4.30398194   1.79070781   3.86415896   4.55530935 
    ## 20170915-H07 20170916-A01 20170916-A03 20170916-A04 20170916-A06 
    ##   6.25176938   0.15707963   2.48185820   6.25176938   0.72256631 
    ## 20170916-A10 20170916-B03 20170916-B07 20170916-B08 20170916-B09 
    ##   1.66504411   1.66504411   6.06327382   4.05265452   6.18893753 
    ## 20170916-B11 20170916-C10 20170916-C11 20170916-D02 20170916-D05 
    ##   5.12079603   2.67035376   4.42964564   4.36681379   2.98451302 
    ## 20170916-D07 20170916-D09 20170916-D10 20170916-D11 20170916-D12 
    ##   4.93230047   4.30398194   3.11017673   4.17831823   3.36150414 
    ## 20170916-E01 20170916-E04 20170916-E09 20170916-E10 20170916-F06 
    ##   5.37212344   5.81194641   4.42964564   1.91637152   4.42964564 
    ## 20170916-F09 20170916-F10 20170916-F12 20170916-G02 20170916-G04 
    ##   5.93761012   1.09955743   1.72787596   4.17831823   4.11548638 
    ## 20170916-G11 20170916-H02 20170916-H04 20170916-H06 20170916-H07 
    ##   0.72256631   2.54469005   1.53938040   4.36681379   4.30398194 
    ## 20170916-H10 20170916-H11 20170917-A01 20170917-A02 20170917-A05 
    ##   1.16238928   4.42964564   1.66504411   1.72787596   3.67566340 
    ## 20170917-A06 20170917-A08 20170917-A09 20170917-A10 20170917-A11 
    ##   1.16238928   4.36681379   2.85884931   4.05265452   3.42433599 
    ## 20170917-A12 20170917-B01 20170917-B02 20170917-B05 20170917-B06 
    ##   1.35088484   1.16238928   0.15707963   1.91637152   0.78539816 
    ## 20170917-B07 20170917-B09 20170917-B11 20170917-C02 20170917-C03 
    ##   2.10486708   3.86415896   6.25176938   5.68628270   1.91637152 
    ## 20170917-C04 20170917-C05 20170917-C07 20170917-C10 20170917-C12 
    ##   4.11548638   4.42964564   1.91637152   0.34557519   4.24115008 
    ## 20170917-D05 20170917-D06 20170917-D09 20170917-D10 20170917-D12 
    ##   1.16238928   4.17831823   4.49247749   1.03672558   1.66504411 
    ## 20170917-E06 20170917-E07 20170917-E08 20170917-E10 20170917-F01 
    ##   4.36681379   4.36681379   0.97389372   1.03672558   0.97389372 
    ## 20170917-F04 20170917-F05 20170917-F06 20170917-F08 20170917-F11 
    ##   4.17831823   1.41371669   4.05265452   3.92699082   3.92699082 
    ## 20170917-F12 20170917-G01 20170917-G02 20170917-G04 20170917-G05 
    ##   4.24115008   2.29336264   2.67035376   4.68097305   4.36681379 
    ## 20170917-G06 20170917-G09 20170917-G11 20170917-H04 20170917-H05 
    ##   4.05265452   1.91637152   1.16238928   2.92168117   0.34557519 
    ## 20170917-H06 20170917-H09 20170917-H10 20170919-A02 20170919-A03 
    ##   2.92168117   4.11548638   4.49247749   0.03141593   1.16238928 
    ## 20170919-A07 20170919-A08 20170919-A09 20170919-A10 20170919-B01 
    ##   5.49778714   4.05265452   1.28805299   4.30398194   1.16238928 
    ## 20170919-B02 20170919-B04 20170919-B05 20170919-B06 20170919-B07 
    ##   4.42964564   3.36150414   0.34557519   0.09424778   1.16238928 
    ## 20170919-B08 20170919-B09 20170919-B10 20170919-B11 20170919-B12 
    ##   1.16238928   1.97920337   4.42964564   0.84823002   4.36681379 
    ## 20170919-C02 20170919-C03 20170919-C06 20170919-C07 20170919-C08 
    ##   1.97920337   1.09955743   0.03141593   2.10486708   0.78539816 
    ## 20170919-C12 20170919-D06 20170919-D08 20170919-D09 20170919-D10 
    ##   0.84823002   4.42964564   1.91637152   4.24115008   1.03672558 
    ## 20170919-D11 20170919-D12 20170919-E01 20170919-E04 20170919-E06 
    ##   0.15707963   0.15707963   0.03141593   1.16238928   1.28805299 
    ## 20170919-E10 20170919-F03 20170919-F05 20170919-F06 20170919-F08 
    ##   5.43495529   0.78539816   5.49778714   1.28805299   1.03672558 
    ## 20170919-F09 20170919-F10 20170919-F11 20170919-F12 20170919-G01 
    ##   2.23053078   4.36681379   4.36681379   4.36681379   0.78539816 
    ## 20170919-G02 20170919-G03 20170919-G05 20170919-G07 20170919-G08 
    ##   0.15707963   4.17831823   4.36681379   1.53938040   1.85353967 
    ## 20170919-G09 20170919-G10 20170919-H03 20170919-H04 20170919-H05 
    ##   0.21991149   1.28805299   1.60221225   4.30398194   4.30398194 
    ## 20170919-H06 20170919-H07 20170919-H11 20170919-H12 20170920-A01 
    ##   4.42964564   4.11548638   4.36681379   0.65973446   3.67566340 
    ## 20170920-A03 20170920-A06 20170920-A07 20170920-A09 20170920-A11 
    ##   6.25176938   0.03141593   4.42964564   1.97920337   1.66504411 
    ## 20170920-A12 20170920-B01 20170920-B04 20170920-B05 20170920-B06 
    ##   1.79070781   4.24115008   0.72256631   2.16769893   4.24115008 
    ## 20170920-B08 20170920-B09 20170920-B10 20170920-B11 20170920-B12 
    ##   1.03672558   0.15707963   1.28805299   1.16238928   2.92168117 
    ## 20170920-C01 20170920-C02 20170920-C03 20170920-C05 20170920-C06 
    ##   0.91106187   4.42964564   0.97389372   2.54469005   2.92168117 
    ## 20170920-C07 20170920-C09 20170920-C11 20170920-C12 20170920-D02 
    ##   5.74911456   5.37212344   1.16238928   4.30398194   0.21991149 
    ## 20170920-D03 20170920-D06 20170920-D08 20170920-D09 20170920-D12 
    ##   1.72787596   1.60221225   0.40840704   1.79070781   2.23053078 
    ## 20170920-E02 20170920-E04 20170920-E05 20170920-E06 20170920-E10 
    ##   0.72256631   0.78539816   1.72787596   1.97920337   4.17831823 
    ## 20170920-E11 20170920-F02 20170920-F05 20170920-F06 20170920-F07 
    ##   0.84823002   4.30398194   0.72256631   1.35088484   1.28805299 
    ## 20170920-F10 20170920-F11 20170920-F12 20170920-G01 20170920-G05 
    ##   1.66504411   3.98982267   1.03672558   0.78539816   5.37212344 
    ## 20170920-G06 20170920-G09 20170920-G12 20170920-H01 20170920-H04 
    ##   4.55530935   6.00044197   4.42964564   0.84823002   4.42964564 
    ## 20170920-H06 20170920-H08 20170920-H10 20170920-H11 20170921-A01 
    ##   4.11548638   1.28805299   0.03141593   1.47654855   4.17831823 
    ## 20170921-A02 20170921-A03 20170921-A05 20170921-A06 20170921-A07 
    ##   3.48716785   3.92699082   5.05796417   5.81194641   4.17831823 
    ## 20170921-A08 20170921-A09 20170921-A10 20170921-A11 20170921-B01 
    ##   2.98451302   4.36681379   4.68097305   5.62345085   6.18893753 
    ## 20170921-B02 20170921-B03 20170921-B05 20170921-B07 20170921-B08 
    ##   4.17831823   5.43495529   4.42964564   4.11548638   4.36681379 
    ## 20170921-B09 20170921-B10 20170921-B11 20170921-C03 20170921-C04 
    ##   3.86415896   4.42964564   3.61283155   0.03141593   4.17831823 
    ## 20170921-C05 20170921-C09 20170921-C10 20170921-C11 20170921-C12 
    ##   0.78539816   4.93230047   3.67566340   4.11548638   4.68097305 
    ## 20170921-D02 20170921-D03 20170921-D05 20170921-D06 20170921-D07 
    ##   5.18362788   6.00044197   4.86946861   0.78539816   0.78539816 
    ## 20170921-D08 20170921-D09 20170921-D10 20170921-D11 20170921-D12 
    ##   5.12079603   5.30929158   6.18893753   2.73318561   6.25176938 
    ## 20170921-E01 20170921-E02 20170921-E04 20170921-E05 20170921-E07 
    ##   4.49247749   0.59690260   0.72256631   4.86946861   4.42964564 
    ## 20170921-E08 20170921-E11 20170921-E12 20170921-F01 20170921-F04 
    ##   4.42964564   4.17831823   2.92168117   6.12610567   5.87477826 
    ## 20170921-F06 20170921-F07 20170921-F08 20170921-F10 20170921-F11 
    ##   4.24115008   4.93230047   3.42433599   4.24115008   5.62345085 
    ## 20170921-G01 20170921-G02 20170921-G04 20170921-G06 20170921-G08 
    ##   4.24115008   6.25176938   4.24115008   0.03141593   6.06327382 
    ## 20170921-G09 20170921-G10 20170921-G12 20170921-H01 20170921-H02 
    ##   4.93230047   3.98982267   2.16769893   5.81194641   4.42964564 
    ## 20170921-H05 20170921-H06 20170921-H07 20170921-H08 20170921-H10 
    ##   4.24115008   4.42964564   5.62345085   4.05265452   4.55530935 
    ## 20170922-A01 20170922-A02 20170922-A04 20170922-A05 20170922-A06 
    ##   0.78539816   4.24115008   1.16238928   4.24115008   4.24115008 
    ## 20170922-A07 20170922-A09 20170922-B03 20170922-B06 20170922-B07 
    ##   0.78539816   0.97389372   1.85353967   4.17831823   1.66504411 
    ## 20170922-B08 20170922-C01 20170922-C02 20170922-C04 20170922-C06 
    ##   1.09955743   1.16238928   1.09955743   4.36681379   5.12079603 
    ## 20170922-C08 20170922-C10 20170922-C11 20170922-D07 20170922-D08 
    ##   1.60221225   0.15707963   4.42964564   0.84823002   4.24115008 
    ## 20170922-D10 20170922-D11 20170922-E02 20170922-E04 20170922-E05 
    ##   4.36681379   0.91106187   4.24115008   4.17831823   3.92699082 
    ## 20170922-E06 20170922-E07 20170922-E08 20170922-E11 20170922-F05 
    ##   1.53938040   4.11548638   5.81194641   0.91106187   1.09955743 
    ## 20170922-F06 20170922-G01 20170922-G04 20170922-G05 20170922-G06 
    ##   1.66504411   4.17831823   1.09955743   4.17831823   3.42433599 
    ## 20170922-G09 20170922-H01 20170922-H03 20170922-H05 20170922-H06 
    ##   4.11548638   4.11548638   0.91106187   4.36681379   0.91106187 
    ## 20170922-H11 20170922-H12 20170924-A01 20170924-A03 20170924-A09 
    ##   4.30398194   4.17831823   4.24115008   4.17831823   1.85353967 
    ## 20170924-A10 20170924-A11 20170924-B02 20170924-B03 20170924-B04 
    ##   5.81194641   1.60221225   3.92699082   1.16238928   6.06327382 
    ## 20170924-B06 20170924-B07 20170924-B09 20170924-B11 20170924-B12 
    ##   4.55530935   0.28274334   1.53938040   1.79070781   0.78539816 
    ## 20170924-C01 20170924-C02 20170924-C03 20170924-C05 20170924-C07 
    ##   1.41371669   0.15707963   1.41371669   1.79070781   4.42964564 
    ## 20170924-C09 20170924-C10 20170924-C11 20170924-D03 20170924-D05 
    ##   1.72787596   4.17831823   3.86415896   0.65973446   6.25176938 
    ## 20170924-D06 20170924-D08 20170924-D12 20170924-E04 20170924-E05 
    ##   1.47654855   1.85353967   0.65973446   5.62345085   1.16238928 
    ## 20170924-E06 20170924-E07 20170924-E08 20170924-E11 20170924-E12 
    ##   4.61814120   2.04203522   6.25176938   1.85353967   0.78539816 
    ## 20170924-F01 20170924-F03 20170924-F07 20170924-F09 20170924-F10 
    ##   1.97920337   2.48185820   4.36681379   4.17831823   4.24115008 
    ## 20170924-F12 20170924-G01 20170924-G04 20170924-G05 20170924-G06 
    ##   4.93230047   4.30398194   0.03141593   1.22522113   1.41371669 
    ## 20170924-G07 20170924-G09 20170924-G12 20170924-H03 20170924-H05 
    ##   3.54999970   1.16238928   1.16238928   4.86946861   2.92168117 
    ## 20170924-H07 20170924-H08 20170924-H11 
    ##   1.60221225   1.53938040   6.18893753

Visualize results of prediction for one gene. Below we choose CDK1.
Because CDK1 is a known cell cycle gene, this visualization serves as a
sanity check for the results of fitting.

``` r
plot(y=assay(sce_top101genes,"cpm_quantNormed")[1,],
     x=colData(sce_top101genes)$theta_shifted, main = "CDK1",
     ylab = "quantile normalized expression")
points(y=training_human$cellcycle_function[[1]](seq(0,2*pi, length.out=100)),
       x=seq(0,2*pi, length.out=100), col = "blue", pch =16)
```

![](README_files/figure-gfm/unnamed-chunk-7-1.png)<!-- -->

### Vignette 2: Making own training data

-----

#### Contact

Please contact me at [joyce.hsiao1@gmail.com](joyce.hsiao1@gmail.com)
for questions on the package or the methods.

#### How to cite

> Hsiao, C. J., Tung, P., Blischak, J. D., Burnett, J., Dey, K. K.,
> Barr, A. K., Stephens, M., and Gilad, Y. (2018). [Characterizing and
> inferring quantitative cell-cycle phase in single-cell RNA-seq data
> analysis.](https://doi.org/10.1101/526848) bioRxiv
> <doi:10.1101/526848>

#### License

Copyright (c) 2019-2020, Joyce Hsiao.

All source code and software in this repository are made available under
the terms of the [GNU General Public
License](https://www.gnu.org/licenses/gpl-3.0.en.html). See file
[LICENSE](LICENSE) for the full text of the license.
